### ISSUE TITLE
Unable to run train.py. Please help as soon as possible.

### ISSUE THREAD

**Issue by yogyamodi** [liuruijin17/LSTR#14]
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 54, in prefetch_data
    raise e
  File "train.py", line 50, in prefetch_data
    data, ind = sample_data(db, ind)
  File "/content/TuSimple/LSTR/sample/tusimple.py", line 80, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind)
  File "/content/TuSimple/LSTR/sample/tusimple.py", line 44, in kp_detection
    img, line_strings, mask = db.transform(image=img, line_strings=line_strings, segmentation_maps=mask)
  File "/usr/local/lib/python3.6/dist-packages/imgaug/augmenters/meta.py", line 1888, in __call__
    return self.augment(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/imgaug/augmenters/meta.py", line 1859, in augment
    batch_aug = self.augment_batch(batch, hooks=hooks)
  File "/usr/local/lib/python3.6/dist-packages/imgaug/augmenters/meta.py", line 424, in augment_batch
    batch = batch.to_normalized_batch()
  File "/usr/local/lib/python3.6/dist-packages/imgaug/augmentables/batches.py", line 213, in to_normalized_batch
    self.segmentation_maps_unaug, shapes),
  File "/usr/local/lib/python3.6/dist-packages/imgaug/augmentables/normalization.py", line 206, in normalize_segmentation_maps
    "SegmentationMapOnImage")
  File "/usr/local/lib/python3.6/dist-packages/imgaug/augmentables/normalization.py", line 62, in _assert_single_array_ndim
    to_ntype, shape_str, ndim, arr.ndim,)
**ValueError: Tried to convert an array to list of SegmentationMapOnImage. Expected that array to be of shape (N,H,W), i.e. 3-dimensional, but got 4 dimensions instead.**

**Comment by liuruijin17** [comment]
Hi, did you change the code or use the imgaug of a different version? 
Please provide more information since others do not seem to have mentioned this issue.
