### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by bclchenliang** [liuruijin17/LSTR#38]
loading from cache file: ./cache\tusimple_['label_data_0313', 'label_data_0601'].pkl
loading from cache file: ./cache\tusimple_['label_data_0531'].pkl
No cache file found...
Now transforming annotations...
len of training db: 3268
len of testing db: 358
freeze the pretrained network: False
start prefetching data...
shuffling indices...
Traceback (most recent call last):
  File "D:\ML\LSTR-main\LSTR-main\train.py", line 50, in prefetch_data
    data, ind = sample_data(db, ind)
  File "D:\ML\LSTR-main\LSTR-main\sample\tusimple.py", line 80, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind)
  File "D:\ML\LSTR-main\LSTR-main\sample\tusimple.py", line 45, in kp_detection
    line_strings.clip_out_of_image_()
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\imgaug\augmentables\lines.py", line 2048, in clip_out_of_image_
    for ls in self.line_strings
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\imgaug\augmentables\lines.py", line 2049, in <listcomp>
    for ls_clipped in ls.clip_out_of_image(self.shape)]
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\imgaug\augmentables\lines.py", line 550, in clip_out_of_image
    intersections = self.find_intersections_with(edges)
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\imgaug\augmentables\lines.py", line 634, in find_intersections_with
    import shapely.geometry
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\software\Miniconda\envs\torch-1.6\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
Process Process-1:
Traceback (most recent call last):
  File "D:\software\Miniconda\envs\torch-1.6\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\software\Miniconda\envs\torch-1.6\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ML\LSTR-main\LSTR-main\train.py", line 54, in prefetch_data
    raise e
  File "D:\ML\LSTR-main\LSTR-main\train.py", line 50, in prefetch_data
    data, ind = sample_data(db, ind)
  File "D:\ML\LSTR-main\LSTR-main\sample\tusimple.py", line 80, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind)
  File "D:\ML\LSTR-main\LSTR-main\sample\tusimple.py", line 45, in kp_detection
    line_strings.clip_out_of_image_()
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\imgaug\augmentables\lines.py", line 2048, in clip_out_of_image_
    for ls in self.line_strings
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\imgaug\augmentables\lines.py", line 2049, in <listcomp>
    for ls_clipped in ls.clip_out_of_image(self.shape)]
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\imgaug\augmentables\lines.py", line 550, in clip_out_of_image
    intersections = self.find_intersections_with(edges)
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\imgaug\augmentables\lines.py", line 634, in find_intersections_with
    import shapely.geometry
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\software\Miniconda\envs\torch-1.6\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\software\Miniconda\envs\torch-1.6\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
start prefetching data...

**Comment by liuruijin17** [comment]
Hi, I see the log mainly raise errors when shuffling image indexes,  
and I think it might be caused by the incompatibility of some packages' version
would you please tell me your hardware and software environment so I can try to fix it?

**Comment by tigerdhl** [comment]
@liuruijin17  I get the same error, how can I fix it?
torch                      1.7.1
torchaudio                 0.7.2
torchvision                0.8.2
tqdm                       4.46.1
my GPU is RTX2060 and CUDA version is cuda_11.0.3_451.82_win10

**Comment by tigerdhl** [comment]
@liuruijin17  I get the same error, how can I fix it?
torch                      1.7.1
torchaudio                 0.7.2
torchvision                0.8.2
tqdm                       4.46.1
my GPU is RTX2060 and CUDA version is cuda_11.0.3_451.82_win10

**Comment by liuruijin17** [comment]
@tigerdhl I have tested on a
python 3.8.5
torch 1.7.1+cu110
CUDA 11.1
RTX 3090
Ubuntu 16.04 
platform. The code works fine.

So maybe it is caused by win10? Could you please test on a Linux environment?
