### ISSUE TITLE
  0%|                                   | 0/500000 [00:00<?, ?it/s]\

### ISSUE THREAD

**Issue by Gooddz1** [liuruijin17/LSTR#40]
Traceback (most recent call last):
  File "/home/goodldz/anaconda3/envs/lstr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/goodldz/anaconda3/envs/lstr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 54, in prefetch_data
    raise e
  File "train.py", line 50, in prefetch_data
    data, ind = sample_data(db, ind)
  File "/media/goodldz/xiaoliu/LSTR-main/LSTR-main/sample/tusimple.py", line 80, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind)
  File "/media/goodldz/xiaoliu/LSTR-main/LSTR-main/sample/tusimple.py", line 38, in kp_detection
    mask  = np.ones((1, img.shape[0], img.shape[1], 1), dtype=np.bool)
AttributeError: 'NoneType' object has no attribute 'shape'
Total parameters: 765787
MACs: 574.280M
setting learning rate to: 0.0001
training start...
  0%|                                   | 0/500000 [00:00<?, ?it/s]\

Does anyone know how to solve this problem

**Comment by liuruijin17** [comment]
Hi, it seems that the image is not loaded correctly, would you please visualize input image and corresponding mask by cv2?
If still goes wrong, please show me more message thx~

**Comment by zhu-del** [comment]
I have the same problem. Have you solved it?
