### ISSUE TITLE
Training fails on Windows 10

### ISSUE THREAD

**Issue by mbirkhez** [liuruijin17/LSTR#44]
The code trains fine on Linux but when I try to train it on Windows 10 with the same steps it results in this error. Any idea what is wrong here?
```
training start...
  0%|                                   | 0/500000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    train(training_dbs, validation_db, args.start_iter, args.freeze) # 0
  File "train.py", line 158, in train
    = nnet.train(iteration, save, viz_split, **training)
  File "C:\Users\mamoo\OneDrive\Documents\GitHub\TuSimple\LSTR\nnet\py_factory.py", line 111, in train
    loss_kp = self.network(iteration,
  File "C:\Users\mamoo\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\mamoo\OneDrive\Documents\GitHub\TuSimple\LSTR\models\py_utils\data_parallel.py", line 66, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids, self.chunk_sizes)
  File "C:\Users\mamoo\OneDrive\Documents\GitHub\TuSimple\LSTR\models\py_utils\data_parallel.py", line 77, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim, chunk_sizes=self.chunk_sizes)
  File "C:\Users\mamoo\OneDrive\Documents\GitHub\TuSimple\LSTR\models\py_utils\scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim, chunk_sizes) if inputs else []
  File "C:\Users\mamoo\OneDrive\Documents\GitHub\TuSimple\LSTR\models\py_utils\scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "C:\Users\mamoo\OneDrive\Documents\GitHub\TuSimple\LSTR\models\py_utils\scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "C:\Users\mamoo\OneDrive\Documents\GitHub\TuSimple\LSTR\models\py_utils\scatter_gather.py", line 20, in scatter_map
    return list(map(list, zip(*map(scatter_map, obj))))
  File "C:\Users\mamoo\OneDrive\Documents\GitHub\TuSimple\LSTR\models\py_utils\scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, chunk_sizes, dim, obj)
  File "C:\Users\mamoo\anaconda3\lib\site-packages\torch\nn\parallel\_functions.py", line 93, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "C:\Users\mamoo\anaconda3\lib\site-packages\torch\nn\parallel\comm.py", line 189, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: start (0) + length (16) exceeds dimension size (1).
```

**Comment by 572693061** [comment]
I have the same problem. Have you solved it now?

**Comment by mbirkhez** [comment]
> I have the same problem. Have you solved it now?

I tried changing / to \ in all the paths but still not running. I think its because of the slash somewhere because this error was coming when the folder structure wasn't like what the author mentioned. But I cannot find where its coming from. I am running the code on Linux for now.
